
[versions]
appcompat = "1.7.1"
bd-capture = "0.21.1"
constraintlayout = "2.2.1"
espressoCore = "3.6.1"
junit = "4.13.2"
junitVersion = "1.2.1"
material = "1.12.0"
navigationFragmentKtx = "2.9.2"
timber = "5.0.1"
#plugins
androidGradlePlugin = "8.12.3"
kotlin = "2.2.20"

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "junitVersion" }
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigationFragmentKtx" }
bd-capture = { module = "io.bitdrift:capture", version.ref = "bd-capture" }
bd-capture-timber = { module = "io.bitdrift:capture-timber", version.ref = "bd-capture" }
junit = { module = "junit:junit", version.ref = "junit" }
material = { module = "com.google.android.material:material", version.ref = "material" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
bd-capture-plugin   = { id = "io.bitdrift.capture-plugin", version.ref = "bd-capture" }
kotlin-android      = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
