[versions]
androidBenchkmarkPlugin = "1.2.4"
androidGradlePlugin = "8.2.2" # have to pin to this version due to 8.3.x breaking our lint https://issuetracker.google.com/issues/332755363
apolloGraphqlPlugin = "3.8.3"
appcompat = "1.5.1"
assertjCore = "3.22.0"
androidxCore = "1.9.0"
androidxTestCore = "1.6.0"
detektPlugin = "1.23.3"
dokkaPlugin = "1.9.20"
gson = "2.10.1"
jsr305 = "3.0.2"
junit = "4.13.2"
kotlinResultJvm = "1.1.18"
lifecycleCommon = "2.6.1"
mavenPublishPlugin = "0.28.0"
kotlinAndroidPlugin = "1.9.24"
mockitoCore = "4.9.0"
mockitoKotlin = "2.2.0"
mockitoKotlinVersion = "4.1.0"
okhttp = "4.12.0"
robolectric = "4.13"
rustAndroidPlugin = "0.9.3"
material3Android = "1.2.1"
startupRuntime = "1.1.1"
timber = "5.0.1"
truth = "1.1.4"
ui = "1.4.0"

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-lifecycle-common = { module = "androidx.lifecycle:lifecycle-common", version.ref = "lifecycleCommon" }
androidx-lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "lifecycleCommon" }
androidx-material3-android = { group = "androidx.compose.material3", name = "material3-android", version.ref = "material3Android" }
androidx-core = { group = "androidx.core", name = "core", version.ref = "androidxCore" }
androidx-startup-runtime = { module = "androidx.startup:startup-runtime", version.ref = "startupRuntime" }
androidx-test-core = { module = "androidx.test:core", version.ref = "androidxTestCore" }
androidx-ui = { module = "androidx.compose.ui:ui", version.ref = "ui" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertjCore" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
jsr305 = { module = "com.google.code.findbugs:jsr305", version.ref = "jsr305" }
junit = { module = "junit:junit", version.ref = "junit" }
kotlin-mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockitoKotlinVersion" }
kotlin-result-jvm = { module = "com.michael-bull.kotlin-result:kotlin-result-jvm", version.ref = "kotlinResultJvm" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockitoCore" }
mockito-inline = { module = "org.mockito:mockito-inline", version.ref = "mockitoCore" }
mockito-kotlin = { module = "com.nhaarman.mockitokotlin2:mockito-kotlin", version.ref = "mockitoKotlin" }
mockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "okhttp" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-benchmark = { id = "androidx.benchmark", version.ref = "androidBenchkmarkPlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
apollo-graphql = { id = "com.apollographql.apollo3", version.ref = "apolloGraphqlPlugin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detektPlugin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokkaPlugin" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "mavenPublishPlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlinAndroidPlugin" }
rust-android = { id = "org.mozilla.rust-android-gradle.rust-android", version.ref = "rustAndroidPlugin" }
