[package]
edition      = "2021"
license-file = "LICENSE"
name         = "capture"
publish      = false
version      = "1.0.0"

[dependencies]
capture-core = { path = "core" }

[lib]
crate-type = ["cdylib"]
name       = "capture"
